### ISSUE TITLE
D7 如何製作月曆 props【 calendar | 我不會寫 React Component 】line 6, 70

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#10]
## line 6
再

> before
> 可以先看完上一篇在接續此篇。

after
可以先看完上一篇再接續此篇。

## line 70
值

> before
> 我會透過這個方式來延展日曆元件的傳入職。

after
我會透過這個方式來延展日曆元件的傳入值。

**Comment by kayac-chang** [comment]
solved
