### ISSUE TITLE
D9 如何製作對話視窗 tabbable【 dialog | 我不會寫 React Component 】line6,18,36,42,

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#12]
## line 6
再
可以先看完上一篇在接續此篇。
可以先看完上一篇再接續此篇。

## line 18
before
以下情況被視為 tabbable:

after 金金完美的～詳加描述後
以下情況將被視為鍵盤可操作 tabbable :

## line 36
before 
- 節點自身或是它的祖宗被 `display: none` 隱藏

after 金金完美的～詳加描述後
- 節點自身或是它的父層元件被 `display: none` 隱藏

## line 42
before
如果你想了解更詳細的清單，可以參考[這個][focusable]。

after 金金完美的～詳加描述後
如果你想了解更詳細的清單，可以參考[這個網站 - Focusable Elements - Browser Compatibility Table][focusable]。

**Comment by kayac-chang** [comment]
solved
