### ISSUE TITLE
D10 如何製作對話視窗 interaction【 dialog | 我不會寫 React Component 】

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#13]
## line 6
再
可以先看完上一篇在接續此篇。
可以先看完上一篇再接續此篇。

## line19
疑問：
好像這句話沒有說完。

原句
- 如果內文太長，對焦在第一個可交互元素會導致畫面滑動到下方時，  
![截圖 2022-09-20 上午11 10 43](https://user-images.githubusercontent.com/87320011/191158965-ce2f1d8b-44fd-4d51-bedb-7bc2c08e27ce.png)

**Comment by kayac-chang** [comment]
solved
