### ISSUE TITLE
D2 專案建置【 我不會寫 React Component 】line11 _monorepo

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#2]
line11 專案建置【 我不會寫 React Component 】_monorepo
註解：Monorepo 簡單的說，是指將公司的所有代碼放到一個 Git / Mercurial / Subversion 的服務當中。

**Comment by kayac-chang** [comment]
> Monorepo 簡單來說，  
> 是指將多個專案放置在同一個專案下集中管理。
> 這樣的好處是在開發階段時，  
> 可以保持開發的彈性，同時也保持解耦。
