### ISSUE TITLE
D2 專案建置【 我不會寫 React Component 】line_292

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#3]
註解：TDD
開發團隊寫測試，通常有三種模式：
先寫測試再開發、開發完成再寫測試、無招勝有招—不寫測試（誤）
TDD是指第一種模式，先寫測試再開發，也就是常聽到的 TDD（Test-Driven Development）。

**Comment by kayac-chang** [comment]
added
