### ISSUE TITLE
D3 如何製作月曆 date grid 【 calendar | 我不會寫 React Component 】line 245

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#5]
![image](https://user-images.githubusercontent.com/87320011/190075998-c0dca5a7-df2d-47f9-9d89-ad162fe7fe6a.png)
---
line 245
 補上文字使語意更清楚， *鍵盤上的按鍵
 
當焦點目前落在元件上時，  
可以用 *鍵盤上的按鍵， 箭頭上下左右 跟 Home, End 下去移動焦點，  
且 `tabindex="0"` 會跟著當前焦點移動。

**Comment by kayac-chang** [comment]
solved
