### ISSUE TITLE
D3 如何製作月曆 date grid 【 calendar | 我不會寫 React Component 】整篇

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#6]
1. 這章的篇幅是在表達，撰寫符合規格的 unit test 嗎？  

2. 這兩段的描述目前空白，看不懂為什麼要放這兩段  
補一些描述文字嗎？  
line 472 Spec: WeekDay Header
line 494 Solution

**Comment by kayac-chang** [comment]
內容會涵蓋：

- Monorepo 的專案架構
- 開發出符合 [WAI][wai] 規格的可達性元件
- 單元測試 跟 E2E 測試
- React Pattern

全部都 **不會很詳細** 的解釋，至少在這個系列我認為不太適合講太多理論。
