### ISSUE TITLE
D4 如何製作月曆 control【 calendar | 我不會寫 React Component 】line6,12,33,181,332

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#7]
### before
可以先看完上一篇 [在] 接續此篇。
### after
再

### before
為此我們需要一個建立兩個按鈕跟一個顯示當前年月的標籤。
### after
為此我們需要
- 一個建立兩個按鈕
- 一個顯示當前年月的標籤

## line 33
`button` 標記 `type="button"` 是 best practice，  
Question :  什麼是 best practice ?

## line 181
![03810AED-0022-4156-947C-6AFEB44F6329_4_5005_c](https://user-images.githubusercontent.com/87320011/190307801-c4b742b6-c5b1-435d-8b37-4c980c74ec3b.jpeg)

## line 332
![24470A8B-EC8B-4E00-AF18-B2577BE03E1B_4_5005_c](https://user-images.githubusercontent.com/87320011/190308544-e2d80419-e9fe-439a-b6f8-1f11b619fd89.jpeg)

**Comment by kayac-chang** [comment]
solved
