### ISSUE TITLE
D5 如何製作月曆 integration【 calendar | 我不會寫 React Component 】line 標題,6,15

### ISSUE THREAD

**Issue by KimberlyYen** [kayac-chang/blog-articles#8]
## 標題
i 是否大寫？
原句：
如何製作月曆 integration【 calendar | 我不會寫 React Component 】
修正後：
如何製作月曆 Integration【 calendar | 我不會寫 React Component 】

## line 6
再
修正後：
可以先看完上一篇再接續此篇。

## line 15
![1FFD0F03-5802-470E-AF34-7888515DE58A_4_5005_c](https://user-images.githubusercontent.com/87320011/190427293-ebbbe90b-62a8-48c3-9a68-b1924e51140c.jpeg)

**Comment by kayac-chang** [comment]
solved
